name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test-pnpm-release:
    name: Test git sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 90dy/ts-lib

      - uses: 90dy/gha-pnpm-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  semantic-release:
    needs: test-pnpm-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 90dy/gha-semantic-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: main
          plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/git
