name: Test pnpm release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test-pnpm-release:
    name: Test git sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 90dy/ts-lib

      - uses: 90dy/gha-pnpm-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
